# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
# * https://github.com/PyCQA/flake8
# * https://github.com/asottile/pyupgrade
name: ci
on:
  push:
    branches: [master]
  pull_request:
    # branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install flake8 pyupgrade
    - run: flake8 --max-line-length=1474
    - run: pyupgrade --py39-plus python/*.py
    - run: |
        autoreconf --install
        ./configure
        make
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install --upgrade pip setuptools
    # - run: python python/setup.py build  # Fails
    # - run: cd python && python setup.py build   # Fails
    # - run: cd python && pip install --editable .  # Fails
    # - run: cd python && pip install .  # Fails
    - run: python/test.py || true  # TODO: Remove `|| true` once the setup.py extension module is fixed.

  # https://pypi.org/project/cibuildwheel
  # build_wheels:
  #  name: Build wheels on ${{ matrix.os }}
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
  #
  #  steps:
  #    - uses: actions/checkout@v4
  #    - run: cp python/setup.py .
  #
  #    # Used to host cibuildwheel
  #    - uses: actions/setup-python@v5
  #
  #    - name: Install cibuildwheel
  #      run: python -m pip install cibuildwheel==2.22.0
  #
  #    - name: Build wheels
  #      run: |
  #        cp python/setup.py .
  #        python -m cibuildwheel --output-dir wheelhouse
  #      # to supply options, put them in 'env', like:
  #      # env:
  #      #   CIBW_SOME_OPTION: value
  #
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
  #        path: ./wheelhouse/*.whl
